[package]
name = "jni_macro"
version = "0.1.0"
edition = "2021"
description = "JNI proc-macro for Android FFI"
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = "1.0.42"
syn = { version = "2.0.110", features = ["full"] }
