[workspace]
members = ["core", "jni_macro"]
resolver = "3"

# [profile.release]
# opt-level = "z"
# lto = "fat"
# codegen-units = 1
# panic = "abort"
# strip = true
# incremental = false

# debug = false
# debug-assertions = false
# overflow-checks = false