[package]
name = "common"
version = "0.1.0"
edition = "2024"

[features]
crypto = ["dep:chacha20poly1305", "dep:hkdf", "dep:x25519-dalek", "dep:sha2"]
msg = []
quic = ["dep:rustls", "dep:rustls-pemfile", "dep:quinn"]

[dependencies]
anyhow = "1.0.100"
chacha20poly1305 = { version = "0.10.1", optional = true }
hkdf = { version = "0.12.4", optional = true }
quinn = { version = "0.11.9", features = ["rustls"], optional = true }
rustls = { version = "0.23.35", features = ["aws-lc-rs"], optional = true }
rustls-pemfile = { version = "2.2.0", optional = true }
serde = { version = "1.0.228", features = ["derive"] }
serde_bytes = "0.11.19"
sha2 = { version = "0.10.9", optional = true }
x25519-dalek = { version = "2.0.1", features = ["static_secrets"], optional = true }
