[package]
name = "resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
quinn = { version = "0.11.9", features = ["rustls"] }
rustls = { version = "0.23.35", features = ["aws-lc-rs"] }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
common = { path = "../common", features = ["msg", "macros"]}
toml = "0.9.8"
url = "2.5.7"
rand = "0.9.2"
crossterm = "0.29.0"
hex = "0.4.3"

[profile.release]
opt-level = 3        # full optimizations
lto = "fat"          # best cross-crate optimization
codegen-units = 1    # maximize inlining (slower build, faster binary)
strip = true         # remove symbols
panic = "abort"      # smaller + faster
