[package]
name = "resolver"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
quinn = { version = "0.11.9", features = ["rustls"] }
rustls = { version = "0.23.35", features = ["aws-lc-rs"] }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.48.0", features = ["full"] }
common = { path = "../common" }
toml = "0.9.8"
url = "2.5.7"
