[package]
name = "common"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bincode = "2.0.1"
chacha20poly1305 = "0.10.1"
hkdf = "0.12.4"
quinn = { version = "0.11.9", features = ["rustls"] }
rand = "0.9.2"
rmp-serde = "1.3.0"
rustls = { version = "0.23.35", features = ["aws-lc-rs"] }
rustls-pemfile = "2.2.0"
serde = { version = "1.0.228", features = ["derive"] }
serde-big-array = "0.5.1"
serde_bytes = "0.11.19"
sha2 = "0.10.9"
x25519-dalek = { version = "2.0.1", features = ["static_secrets"] }
