match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
comment_width = 100
format_code_in_doc_comments = true
imports_granularity = "Item"
imports_layout = "Vertical"
wrap_comments = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_small_heuristics = "Max"
fn_params_layout = "Compressed"