[network]
address = "0.0.0.0:4432"
cert_path = "cert/relay.crt"
key_path = "cert/relay.key"
root_ca_path = "cert/root_ca.pem"

[[resolver.seed]]
# Resolver's Identity Public Key
key = "A038F54EC3EBC391F423236E0091413C7275EFEDC65E89D3BFF9DF055FEFE4CC"
addr = "192.168.100.2:4433"