name: Relay

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout THIS repo into project/
      - uses: actions/checkout@v4
        with:
          path: project

      # checkout the sibling repo into ../common
      - uses: actions/checkout@v4
        with:
          repository: promtuz/common
          path: common

      - name: Build
        working-directory: project
        run: cargo build --verbose

      - name: Test
        working-directory: project
        run: cargo test --verbose
