name: Relay CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v4
      with:
        path: main

    - name: Setup SSH key for common repo
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.COMMON_DEPLOY_KEY }}

    - name: Checkout common crate
      uses: actions/checkout@v4
      with:
        repository: promtuz/common
        ssh-key: ${{ secrets.COMMON_DEPLOY_KEY }}
        path: common

    - name: Setup Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        cache: true

    - name: Build
      working-directory: ./main
      run: cargo build --verbose

    - name: Run tests
      working-directory: ./main
      run: cargo test --verbose

    - name: Run clippy
      working-directory: ./main
      run: cargo clippy -- -D warnings

    - name: Check formatting
      working-directory: ./main
      run: cargo fmt -- --check